strip trailing whitespace from project name
MerginMaps/qgis-plugin pull request #577
Opened 2024-03-15 09:16 UTC by JanCaha

Strip spaces from Project Name in Create new project window.

Fix #552

2024-09-11 13:45 UTC, ValentinBuira approved these changes

2024-09-12 14:07 UTC, alexd0793 commented
Error on qgis plugin when trying to create a project with spaces at the beginning and at the end of it's name 
![image](https://github.com/user-attachments/assets/17857a0f-85ec-482c-9cd4-f7fc444bc23d)

2024-09-18 12:46 UTC, ValentinBuira requested changes
This fail to create the project:
* On windows see  comment from @alexd0793 on the PR
*  On server side : 
![image](https://github.com/user-attachments/assets/4faca3bc-ee55-4205-92d3-728ce546f77f)
(actually the project is created on the server side but is not accessible from the plugin)

Do you think you could have a look @JanCaha ?

2024-09-20 09:37 UTC, ValentinBuira commented
Thanks @JanCaha , looking good now merging then :-)

2024-09-20 09:38 UTC, merged